# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
           python-version: 3.9
           cache: 'pip'
     
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Build
        run: pelican  content -o ./output -s "publishconf.py"

      - name: Cloudflare Pages GitHub Action
        # You may pin to the exact commit or the version.
        # uses: cloudflare/pages-action@752c4fc911d149221a4173136118c3cc250e9409
        uses: cloudflare/pages-action@1.0.0
        with:
          # Cloudflare API Token
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Cloudflare Account ID
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # The name of the Pages project to upload to
          projectName: liantian-log
          # The directory of static assets to upload
          directory: output
          # GitHub Token
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      
